import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { SelectNative } from "@/components/ui/select";
import { createAccount, createCategory, createMovement, createSavingsGoal, createWorkspace, inviteMember } from "@/lib/actions";
import type { Account, Category, Workspace } from "@/types/database";

export function WorkspaceForm() { return <Card><CardHeader><CardTitle>Nuevo workspace</CardTitle></CardHeader><CardContent><form action={createWorkspace} className="grid gap-3"><Label>Nombre</Label><Input name="name" required /><SelectNative name="type"><option value="shared">Compartido</option><option value="personal">Personal</option></SelectNative><Button>Crear</Button></form></CardContent></Card>; }
export function InviteForm({ workspaceId }: { workspaceId: string }) { return <Card><CardHeader><CardTitle>Invitar miembro</CardTitle></CardHeader><CardContent><form action={inviteMember} className="grid gap-3"><input type="hidden" name="workspace_id" value={workspaceId} /><Label>Email</Label><Input name="email" type="email" required /><SelectNative name="role"><option value="member">Miembro</option><option value="admin">Admin</option></SelectNative><Button>Enviar invitación</Button></form></CardContent></Card>; }
export function AccountForm() { return <Card><CardHeader><CardTitle>Nueva cuenta</CardTitle></CardHeader><CardContent><form action={createAccount} className="grid gap-3"><Input name="name" placeholder="Nombre" required /><SelectNative name="type"><option value="cash">Efectivo</option><option value="bank">Banco</option><option value="wallet">Billetera</option><option value="other">Otra</option></SelectNative><SelectNative name="currency"><option>ARS</option><option>USD</option></SelectNative><Input name="initial_balance" type="number" step="0.01" placeholder="Saldo inicial" /><Button>Crear cuenta</Button></form></CardContent></Card>; }
export function CategoryForm({ workspaces }: { workspaces: Workspace[] }) { return <Card><CardHeader><CardTitle>Nueva categoría</CardTitle></CardHeader><CardContent><form action={createCategory} className="grid gap-3"><SelectNative name="workspace_id">{workspaces.map((w) => <option key={w.id} value={w.id}>{w.name}</option>)}</SelectNative><Input name="name" placeholder="Nombre" required /><SelectNative name="kind"><option value="income">Ingreso</option><option value="expense">Gasto</option></SelectNative><Input name="color" type="color" defaultValue="#0f766e" /><Button>Crear categoría</Button></form></CardContent></Card>; }
export function MovementForm({ workspaces, accounts, categories }: { workspaces: Workspace[]; accounts: Account[]; categories: Category[] }) { return <Card><CardHeader><CardTitle>Nuevo movimiento</CardTitle></CardHeader><CardContent><form action={createMovement} className="grid gap-3"><SelectNative name="workspace_id">{workspaces.map((w) => <option key={w.id} value={w.id}>{w.name}</option>)}</SelectNative><SelectNative name="type"><option value="income">Ingreso</option><option value="expense">Gasto</option><option value="transfer">Transferencia</option></SelectNative><Input name="amount" type="number" step="0.01" required placeholder="Monto" /><SelectNative name="currency"><option>ARS</option><option>USD</option></SelectNative><Input name="date" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} /><SelectNative name="account_id">{accounts.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</SelectNative><SelectNative name="transfer_account_id"><option value="">Cuenta destino (solo transferencias)</option>{accounts.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</SelectNative><SelectNative name="category_id"><option value="">Sin categoría</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</SelectNative><Input name="description" placeholder="Descripción" /><Button>Crear movimiento</Button></form></CardContent></Card>; }
export function GoalForm({ workspaces }: { workspaces: Workspace[] }) { return <Card><CardHeader><CardTitle>Nuevo objetivo</CardTitle></CardHeader><CardContent><form action={createSavingsGoal} className="grid gap-3"><SelectNative name="workspace_id">{workspaces.map((w) => <option key={w.id} value={w.id}>{w.name}</option>)}</SelectNative><Input name="name" required placeholder="Nombre" /><Input name="target_amount" type="number" step="0.01" required placeholder="Monto objetivo" /><Input name="current_amount" type="number" step="0.01" placeholder="Monto actual" /><SelectNative name="currency"><option>ARS</option><option>USD</option></SelectNative><Input name="target_date" type="date" /><Button>Crear objetivo</Button></form></CardContent></Card>; }
