import { deleteSavingsGoal, updateSavingsGoal, updateSavingsGoalProgress } from "@/lib/actions";
import type { SavingsGoal } from "@/types/database";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { SelectNative } from "@/components/ui/select";

export function GoalActions({ goal }: { goal: SavingsGoal }) {
  return <div className="grid gap-3 border-t pt-3"><details><summary className="cursor-pointer text-sm font-medium text-teal-700">Actualizar progreso</summary><form action={updateSavingsGoalProgress} className="mt-3 flex gap-2"><input type="hidden" name="id" value={goal.id} /><Input aria-label="Monto actual" name="current_amount" type="number" min="0" step="0.01" defaultValue={Number(goal.current_amount)} required /><Button size="sm">Actualizar</Button></form></details><details><summary className="cursor-pointer text-sm font-medium text-slate-700">Editar objetivo</summary><form action={updateSavingsGoal} className="mt-3 grid gap-3 rounded-xl bg-slate-50 p-3"><input type="hidden" name="id" value={goal.id} /><input type="hidden" name="workspace_id" value={goal.workspace_id} /><Label>Nombre</Label><Input name="name" defaultValue={goal.name} required /><Label>Monto objetivo</Label><Input name="target_amount" type="number" min="0.01" step="0.01" defaultValue={Number(goal.target_amount)} required /><Label>Monto actual</Label><Input name="current_amount" type="number" min="0" step="0.01" defaultValue={Number(goal.current_amount)} required /><Label>Moneda</Label><SelectNative name="currency" defaultValue={goal.currency}><option>ARS</option><option>USD</option></SelectNative><Label>Fecha objetivo</Label><Input name="target_date" type="date" defaultValue={goal.target_date ?? ""} /><Button size="sm">Guardar cambios</Button></form></details><form action={deleteSavingsGoal}><input type="hidden" name="id" value={goal.id} /><Button type="submit" size="sm" variant="destructive">Eliminar objetivo</Button></form></div>;
}
