import { DashboardCharts } from "@/components/dashboard-charts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { SelectNative } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { getDashboardData } from "@/lib/data";
import { formatMoney } from "@/lib/utils";

type Search = { workspace?: string; currency?: "ARS" | "USD" };
export default async function DashboardPage({ searchParams }: { searchParams: Promise<Search> }) {
  const params = await searchParams;
  const data = await getDashboardData(params.workspace, params.currency ?? "ARS");
  return <div className="space-y-6">{data.onboardingError ? <p className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{data.onboardingError}</p> : null}<header className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h1 className="text-3xl font-bold tracking-tight">Dashboard</h1><p className="text-slate-500">Resumen mensual, saldos y movimientos recientes.</p></div><form className="flex gap-2"><SelectNative name="workspace" defaultValue={data.activeWorkspace ?? undefined}>{data.workspaces.map((w) => <option key={w.id} value={w.id}>{w.name}</option>)}</SelectNative><SelectNative name="currency" defaultValue={params.currency ?? "ARS"}><option>ARS</option><option>USD</option></SelectNative><button className="rounded-xl bg-teal-700 px-4 text-sm font-medium text-white">Filtrar</button></form></header><section className="grid gap-4 md:grid-cols-4">{[["Patrimonio", data.metrics.netWorth], ["Ingresos mes", data.metrics.income], ["Gastos mes", data.metrics.expense], ["Balance", data.metrics.balance]].map(([label, value]) => <Card key={label as string}><CardHeader><CardTitle className="text-sm text-slate-500">{label}</CardTitle></CardHeader><CardContent><p className="text-2xl font-bold">{formatMoney(value as number, params.currency ?? "ARS")}</p></CardContent></Card>)}</section><DashboardCharts series={data.series} expensesByCategory={data.expensesByCategory} /><section className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Saldo por cuenta</CardTitle></CardHeader><CardContent>{data.accounts.map((account) => <div key={account.id} className="flex justify-between border-b py-3 last:border-0"><span>{account.name}</span><strong>{formatMoney(Number(account.current_balance), account.currency)}</strong></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Movimientos recientes</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Fecha</TableHead><TableHead>Tipo</TableHead><TableHead>Monto</TableHead></TableRow></TableHeader><TableBody>{data.movements.filter((movement) => !movement.is_reversed).slice(0, 8).map((m) => <TableRow key={m.id}><TableCell>{m.date}</TableCell><TableCell>{m.type}</TableCell><TableCell>{formatMoney(Number(m.amount), m.currency)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></section></div>;
}
